name: VitePress Deployment

on:
  push:
    branches:
      - vp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: vp

      - name: ğŸš§ Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: ğŸš€ Build VitePress application
        run: |
          pnpm run build

      - name: ğŸ‰ Commit and push changes to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          commit_message: ğŸ“ ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          cname: docs.sayu-bot.com
